[theme]
primaryColor="#383838"
backgroundColor="#fff"
secondaryBackgroundColor="#e5ecf2"
textColor="#383838"
font="sans serif"

#[server] 
#headless = true
#port = 8501
#enableCORS = true 

#[browser]
#serverAddress = "www.varmepumpeinfo.no"
#gatherUsageStats = false
